[6/2/2025, 9:23:59 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary --version
legendary version "0.20.37", codename "Exit 17 (Heroic)"
[6/2/2025, 9:24:01 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary list --third-party
[cli] INFO: Logging in...
[Core] INFO: Logging in...
[6/2/2025, 9:24:02 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary cleanup
[EPCAPI] ERROR: Login to EGS API failed with errorCode: errors.com.epicgames.account.auth_token.invalid_refresh_token
[Core] ERROR: Stored credentials are no longer valid! Please login again.
[cli] ERROR: Login failed, cannot continue!
[cli] INFO: Cleanup complete! Removed 1.49 MiB.
[6/2/2025, 9:44:20 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 8e4f8dc250364e30aef276555bba1734 --json --platform Windows
[6/2/2025, 9:44:20 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 8e4f8dc250364e30aef276555bba1734 --json --platform Windows
[Core] INFO: Fetching metadata for 117 app(s).
[Core] WARNING: Fetching metadata for 007ff8f4e30845a687e66aa77eb3e965 failed, retrying
Traceback (most recent call last):
  File "legendary/cli.py", line 3286, in <module>
  File "legendary/cli.py", line 3223, in main
  File "legendary/cli.py", line 1672, in info
  File "legendary/core.py", line 397, in get_game
  File "legendary/core.py", line 401, in get_game_list
  File "legendary/core.py", line 496, in get_game_and_dlc_list
  File "legendary/core.py", line 453, in fetch_game_meta
  File "legendary/api/egs.py", line 213, in get_game_info
  File "requests/models.py", line 1024, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://catalog-public-service-prod06.ol.epicgames.com/catalog/api/shared/namespace/a93cd6111251461c953776a0c4ea4d80/bulk/items?id=d0083c0713b140709d92ac02b179cbf2&includeDLCDetails=True&includeMainGameDetails=True&country=US&locale=en
[PYI-8797:ERROR] Failed to execute script 'cli' due to unhandled exception!
[6/2/2025, 9:44:29 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 8e4f8dc250364e30aef276555bba1734 --json --platform Windows
[6/2/2025, 9:44:29 AM] LEGENDARY_CONFIG_PATH=/home/dorrel/.config/heroic/legendaryConfig/legendary /opt/Heroic/resources/app.asar.unpacked/build/bin/x64/linux/legendary info 8e4f8dc250364e30aef276555bba1734 --json --platform Windows
[Core] INFO: Fetching metadata for 117 app(s).
[Core] WARNING: Fetching metadata for 007ff8f4e30845a687e66aa77eb3e965 failed, retrying
Traceback (most recent call last):
  File "legendary/cli.py", line 3286, in <module>
  File "legendary/cli.py", line 3223, in main
  File "legendary/cli.py", line 1672, in info
  File "legendary/core.py", line 397, in get_game
  File "legendary/core.py", line 401, in get_game_list
  File "legendary/core.py", line 496, in get_game_and_dlc_list
  File "legendary/core.py", line 453, in fetch_game_meta
  File "legendary/api/egs.py", line 213, in get_game_info
  File "requests/models.py", line 1024, in raise_for_status
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://catalog-public-service-prod06.ol.epicgames.com/catalog/api/shared/namespace/a93cd6111251461c953776a0c4ea4d80/bulk/items?id=d0083c0713b140709d92ac02b179cbf2&includeDLCDetails=True&includeMainGameDetails=True&country=US&locale=en
[PYI-8832:ERROR] Failed to execute script 'cli' due to unhandled exception!
